web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - ./web
      - /web/node_modules/
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/bash -c "yarn && yarn start"
