web:
    build: ./mccv-frontend/
    ports:
      - '8080:8080'
    volumes:
      - ./mccv-frontend/web
      - /app/node_modules/
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: /bin/bash -c "yarn && yarn start"
